((nil . ((standard-indent . 4)
         (tab-width . 4)
         (web-mode-markup-indent-offset . 4)
         (web-mode-css-indent-offset . 4)
         (web-mode-code-indent-offset . 4)
         (web-mode-attr-indent-offset . 4)
         (web-mode-attr-value-indent-offset . 4)
         (web-mode-indent-style . 4)
         )))
